### PR TITLE
Fix migrations, Add perf logging, id search limit shortcut

### LINKED ISSUE #177: Pagination error
Originally discovered [here](https://github.com/stac-utils/stac-fastapi-pgstac/actions/runs/4782724147/jobs/8510628506#step:7:4763), pagination appears to be broken in v0.7.4. Things work ok in v0.7.3. Minimum reproducible example (a simple test in `004_search.sql`):

```diff
diff --git a/src/pgstac/tests/pgtap/004_search.sql b/src/pgstac/tests/pgtap/004_search.sql
index 85d15e4..acc6d3a 100644
--- a/src/pgstac/tests/pgtap/004_search.sql
+++ b/src/pgstac/tests/pgtap/004_search.sql
@@ -68,6 +68,10 @@ SELECT results_eq($$
 );
 
 
+SELECT search('{"collections": ["pgstac-test-collection"], "limit": 1}');
+SELECT search('{"collections": ["pgstac-test-collection"], "limit": 1, "token": "next:pgstac-test-item-0001"}');
+
+
 SELECT has_function('pgstac'::name, 'search_query', ARRAY['jsonb','boolean','jsonb']);
```

fails with

```
psql:tests/pgtap/004_search.sql:72: ERROR:  syntax error at or near ")"
LINE 1: ...WHERE collection = ANY ('{pgstac-test-collection}')  AND ();
                                                                     ^
QUERY:  EXPLAIN (format json) SELECT 1 FROM items WHERE collection = ANY ('{pgstac-test-collection}')  AND ();
CONTEXT:  PL/pgSQL function chunker(text) line 8 at EXECUTE
PL/pgSQL function search_rows(text,text,text[],integer) line 25 at FOR over SELECT rows
SQL statement "SELECT jsonb_agg(format_item(i, _fields, hydrate))                      FROM search_rows(
        full_where,
        orderby,
        search_where.partitions,
        _querylimit
    ) as i"
PL/pgSQL function search(jsonb) line 66 at SQL statement
```

### LINKED ISSUE #180: Migration fails from 0.7.4
Hello,

We are trying to upgrade from `0.7.4` to newer versions and we see this error during `pypgstac migrate`:

```
pypgstac migrate
Traceback (most recent call last):
  File "/srv/conda/bin/pypgstac", line 8, in <module>
    sys.exit(cli())
  File "/srv/conda/lib/python3.10/site-packages/pypgstac/pypgstac.py", line 118, in cli
    fire.Fire(PgstacCLI)
  File "/srv/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/srv/conda/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/srv/conda/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/srv/conda/lib/python3.10/site-packages/pypgstac/pypgstac.py", line 57, in migrate
    return migrator.run_migration(toversion=toversion)
  File "/srv/conda/lib/python3.10/site-packages/pypgstac/migrate.py", line 144, in run_migration
    cur.execute(migration_sql)
  File "/srv/conda/lib/python3.10/site-packages/psycopg/cursor.py", line 557, in execute
    raise ex.with_traceback(None)
psycopg.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

No further error messages are available.

### PR DESCRIPTION
**Pull request by bitner**
### Fixed
- Fix migrations for 0.7.4->0.7.5 and 0.7.5->0.7.6 to use the partition_view rather than the materialized view to avoid issue with refreshing the materialized view when run in the same statement that is accessing the view. Fixes #180.
  
### Added
- Add a short cirucit for id searches that sets the limit to be no more than the number of ids in the filter.
- Add 'timing' configuration variable that adds a "timing" element to the return object with the amount of time that it took to return a search.
- Reduce locking when updating statistics in the search table. Use skip locked to skip updating last_used and count when there is a lock being held.

### CODE REVIEW

File: src/pgstac/sql/004_search.sql [hunk 1]
```diff
@@ -760,11 +779,22 @@ DECLARE
...
     _querylimit int;
     _fields jsonb := coalesce(_search->'fields', '{}'::jsonb);
     has_prev boolean := FALSE;
     has_next boolean := FALSE;
+    items_cnt int := coalesce(jsonb_array_length(_search->'ids'),0);
 BEGIN
+    RAISE NOTICE 'Items Count: %', items_cnt;
+    IF items_cnt > 0 THEN
+        IF items_cnt <= _limit THEN
+            _limit := items_cnt - 1;
```
Comment (mmcfarland) [inline src/pgstac/sql/004_search.sql:792]: Just following the logic here: the subtraction is so that when the search limit is bumped by 1 to check to see if it needs a "next token", it evens out and still doesn't keep scanning?

**Review by mmcfarland — APPROVED** [review]

File: src/pgstac/sql/004_search.sql (hunk 1 above)
Comment (bitner) [reply src/pgstac/sql/004_search.sql:792]: yep, otherwise it would keep scanning for a next item which we know it wouldn't find
