### PR TITLE
Search bugfixes

### LINKED ISSUE #9: Errors on fresh run of `psql -f pgstac.sql`
Tried `psql -f pgstac.sql` on an empty PostgreSQL 12 GCP Cloud SQL database on commit d60d7e80c18fee64fd02e76e17e37a88d42a9608 and got some errors, especially:

```
psql:sql/003_items.sql:269: NOTICE:  trigger "items_stmt_trigger" for relation "items" does not exist, skipping
psql:sql/004_search.sql:191: ERROR:  return type mismatch in function declared to return box3d
```

Here's the full output:

```
BEGIN
CREATE EXTENSION
CREATE SCHEMA
CREATE EXTENSION
CREATE SCHEMA
SET
CREATE TABLE
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
SET
CREATE TABLE
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
SET
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
DELETE 0
 create_parent 
---------------
 t
(1 row)

CREATE FUNCTION
CREATE FUNCTION
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TYPE
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
psql:sql/003_items.sql:269: NOTICE:  trigger "items_stmt_trigger" for relation "items" does not exist, skipping
DROP TRIGGER
CREATE TRIGGER
CREATE VIEW
CREATE VIEW
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
SET
DROP VIEW
CREATE VIEW
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
psql:sql/004_search.sql:191: ERROR:  return type mismatch in function declared to return box3d
DETAIL:  Actual return type is geometry.
CONTEXT:  SQL function "bbox_geom"
psql:sql/004_search.sql:195: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:sql/004_search.sql:199: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:sql/004_search.sql:259: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:sql/004_search.sql:279: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:sql/004_search.sql:288: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:sql/004_search.sql:330: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:sql/004_search.sql:361: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:sql/004_search.sql:371: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:sql/004_search.sql:595: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

### LINKED ISSUE #10: query operators should match spec
Here a list of operators are defined to include `le` and `ge`: https://github.com/stac-utils/pgstac/blob/main/sql/004_search.sql#L218-L230

The [spec](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/query) has these as `lte` and `gte`

### LINKED ISSUE #12: Token Pagination not following full datetime filter.
The code to add the temporal component to queries with pagination is not appropriately intersecting the token datetime with the query datetime.

### PR DESCRIPTION
**Pull request by bitner**
- Fix for datetime filtering when using pagination (Fixes #12)
- Fix to use lte and gte rather than le and ge to match STAC spec (Fixes #10)
- Fix to change return type for bbox_geom function to geometry (Fixes #9)

### CODE REVIEW

File: sql/004_search.sql [hunk 1]
```diff
@@ -218,8 +218,8 @@ prop_path := replace(att_parts.dotpath, 'properties.', '');
 op := CASE _op
     WHEN 'eq' THEN '='
     WHEN 'ge' THEN '>='
-    WHEN 'gt' THEN '>'
-    WHEN 'le' THEN '<='
+    WHEN 'gte' THEN '>'
```
Comment (lossyrob) [inline sql/004_search.sql:221]: @bitner  this will break the pgstac backend of fast-api, no? Because of [these operators](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/pgstac/stac_fastapi/pgstac/types/search.py#L25-L27)?

Comment (bitner) [reply sql/004_search.sql:221]: yes. the backend is pegged to 0.2.4, so will need to update stac-fastapi pgstac with this and change the pin to 0.2.5

Comment (zstatmanweil) [reply sql/004_search.sql:221]: hi @bitner and @lossyrob: I ended up on this PR as I was encountering the issue - thanks for fixing it! I think the greater than's got mixed up. Should be the following to match the change happening with the less than's:
```sql
WHEN 'gt' THEN '>'
WHEN 'gte' THEN '>='
```
Should I open a PR to fix this?

Comment (lossyrob) [reply sql/004_search.sql:221]: Yes! Great catch...a PR would be appreciated, thank you!

Comment (zstatmanweil) [reply sql/004_search.sql:221]: @lossyrob, will you make me a collaborator so I can open the PR? Fixed the issue but don't have access. I imagine I may contribute in the future anyhow

Comment (lossyrob) [reply sql/004_search.sql:221]: Ah, the best way to make a PR would be to fork the project into your GitHub account, clone that repo (or add your fork as a remote, e.g. `git remote add mine git@github.com:/zstatmanweil/pgstac`, push the branch to your fork (`git push mine my-fix-branch`), and then make the PR from their to the main stac-utils/pgstac GitHub repository. Would that work for you? You can make PRs against this project in that way, and also any other open source project even if your not a collaborator.

Comment (zstatmanweil) [reply sql/004_search.sql:221]: Got it - thanks for the explanation. PR opened!
